### PR TITLE
fix: email case sensitivity

### LINKED ISSUE #134: Email addresses are being treated as case-sensitive when logging in

### PR DESCRIPTION
**Pull request by RegsonDR**
#134 
For authentication and getUserByEmail

### CODE REVIEW

**Review by amishshah — CHANGES_REQUESTED** [review]
I think a better long-term fix here would be to lowercase the emails before storing them in the database. Could you change it to do that?

Once it's merged, I'll update all the emails in the database to be lowercase to avoid any issues.

**Comment by RegsonDR** [comment]
@amishshah Done, I left the "lower(user.email)" in the query in case anyone doesn't update their local db or do you think I should remove those too? In reference to line 108 & 125.

**Comment by amishshah** [comment]
> @amishshah Done, I left the "lower(user.email)" in the query in case anyone doesn't update their local db or do you think I should remove those too? In reference to line 108 & 125.

Could you remove these too? Just to avoid confusion in the future about whether or not the emails are already lowercase in the database.

**Comment by amishshah** [comment]
Note this would also require updating other places where we query by email (e.g. when resetting password, the user has to provide their email. This should be lowercased before querying)

**Comment by RegsonDR** [comment]
>Could you remove these too? Just to avoid confusion in the future about whether or not the emails are already lowercase in the database.

Sure this has been done. 

>Note this would also require updating other places where we query by email (e.g. when resetting password, the user has to provide their email. This should be lowercased before querying)

This has been updated for forgotPassword() but not resetPassword(), it looks like for resetPassword you use the userID, let me know if I misinterpreted it though.

**Review by amishshah — APPROVED** [review]
LGTM! I'll just add some tests to make sure this works as expected, then merge in time for tomorrow.

**Pull request merged**
